<?php
/*
 * Copyright (c) 2020 Payout One
 *
 * Author: Web Technology Codes Software Services LLP
 * 
 * Released under the GNU General Public License
 */
?>
<?php if ($instructions = $block->getMethod()->getInstructions()): ?>
    <div class="items <?php echo $block->getMethodCode() ?> instructions agreement content" id="payment_form_<?php echo $block->getMethodCode() ?>" style="display: none;">
        <?php echo nl2br($block->escapeHtml($instructions)) ?>
    </div>
<?php endif; ?>